### ISSUE TITLE
No Fachgruppe specific rules displayed

### ISSUE THREAD

**Issue by janmax** [frissdiegurke/murderer.js#2]
Please add specific rules that manage things like double kills or witnessing murders.

**Comment by frissdiegurke** [comment]
You mean within plain text rules, right?

To be considered within the PPPPPPS :memo: of my latest multicast email:

> Falls jemand die home-seite mal uebersetzen/ueberarbeiten und/oder Regeln ausschreiben moechte (explizit fuer murderer.js, kein plagiat) (gerne auch dies uebersetzen), kann er/sie gerne texte einschicken (entweder per mail oder PR auf GitHub).

In english:

> If someone is willing to translate/rework the home page and/or write the rules down (explicitly for murderer.js, no plagiarism) (preferred including translation likewise), he/she is pleased to send in those (either via email or Pull Request).

All in all I'm currently not working on those major text contents of the application and would appreciate any help on this :wink:.

**Comment by frissdiegurke** [comment]
English translation still missing, but this the OP is done within development branch.
