### ISSUE TITLE
no secure connection

### ISSUE THREAD

**Issue by Feconi** [frissdiegurke/murderer.js#48]
The image of the game sIT2016 is not transmitted encrypted.
`<img alt="dammit, emacs" src="http://imgs.xkcd.com/comics/real_programmers.png">`
Because of that some browsers (like my mobile's) refuse to connect to frissdiegurke.com after once loading the page with that image.
There may be some other images wich aren't transmitted encrypted.
Please ensure that this does not happen.

**Comment by frissdiegurke** [comment]
Please only report problems with the application itself, not with any instances that are hosted.
